name: Deploy to GKE

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Login to Docker Hub
      uses: azure/container-actions/docker-login@master
      with:
        login-server: docker.io
        username: {{`${{ secrets.DOCKER_HUB_USERNAME }}`}}
        password: {{`${{ secrets.DOCKER_HUB_PASSWORD }}`}}
    
    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push
        
    - name: Deploy from Compose to Kubernetes
      uses: 'docker://sixeyed/gcp-gke-stack-deploy:latest'          
      env:
        GCP_SA_KEY_ENCODED: {{`${{ secrets.GCP_SA_KEY_ENCODED }}`}}
        GCP_PROJECT_ID: {{`${{ secrets.GCP_PROJECT_ID }}`}}
        GCP_ZONE: {{`${{ secrets.GCP_ZONE }}`}}
        DOCKER_COMPOSE_PATH: '/github/workspace/docker-compose.yaml'
        DOCKER_STACK_NAME: guestbook